version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17  # Usa Java 17 para rodar o Maven
    commands:
      - echo "Instalando Trivy..."
      - sudo apt update
      - sudo apt install -y trivy

  build:
    commands:
      - echo "Compilando o projeto com Maven..."
      - cd java-maven-sonar-argocd-helm-k8s/spring-boot-app
      - mvn clean verify package -DskipTests=false

      - echo "Construindo a imagem Docker..."
      - docker build -t jorgejardimneto/ultimate-cicd:$CODEBUILD_BUILD_NUMBER .

      - echo "Rodando análise de vulnerabilidades com Trivy..."
      - trivy image --severity HIGH,CRITICAL --format json -o trivy-report.json jorgejardimneto/ultimate-cicd:$CODEBUILD_BUILD_NUMBER

  post_build:
    commands:
      - echo "Análise concluída! Salvando resultados no S3..."
      - aws s3 cp trivy-report.json s3://meu-bucket-de-relatorios/
